### ISSUE TITLE
fatalError-function not allowing empty call

### ISSUE THREAD

**Issue by weyert** [remobjects/SwiftBaseLibrary#10]
The `fatalError`-function doesn't support the common call `fatalError()` as seen in Swift projects

Now I have to admit I tried to solve this but couldn't see a good solution as `message` is a closure and in Swift's `stdlib` defined as: 

`func fatalError(_ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line) -> Never`

The `String()` is not working in our case

**Comment by dwarfland** [comment]
thanx, fixed.
